# Generated by Django 5.0.6 on 2024-05-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "nickname",
                    models.CharField(max_length=255, unique=True, verbose_name="닉네임"),
                ),
                ("mbti", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(max_length=255, verbose_name="휴대전화번호"),
                ),
                ("profile_img", models.URLField(max_length=255)),
                ("is_staff", models.BooleanField(default=False, verbose_name="운영진")),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="챌린지 도전 회원"),
                ),
                ("is_down", models.BooleanField(default=False, verbose_name="휴면회원")),
                ("is_active", models.BooleanField(default=True, verbose_name="활동회원")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="가입일자"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일자"),
                ),
            ],
        ),
    ]
